### ISSUE TITLE
Inlay hint is not working when calling child's methods

### ISSUE THREAD

**Issue by teodor-t-tenev** [hostar/python-inlay-putter#2]
Test with the following code:

``` python
class Child:
    def print_word(self, word):
        print(word)


class Parent:
    def __init__(self):
        self.child = Child()
    
    @property
    def get_child(self):
        return Child()


a = Parent()
a.child.print_word('not working')    #inlay is not shown
a.get_child.print_word('not working')   #inlay is not shown
```

![image](https://user-images.githubusercontent.com/89847855/137630516-093cdf16-43e0-48f4-a847-501d13b7d5f6.png)

**Comment by hostar** [comment]
Same as before: https://github.com/hostar/python-inlay-putter/releases/tag/0.0.5
This fix was not even that dirty 😃

**Comment by teodor-t-tenev** [comment]
Seems to be working if called directly from the same module. But if you call it from other module it is not working again.

E.g. create 
**Main.py** ->

```python
class Child:
    def print_word(self, word):
        print(word)


class Parent:
    def __init__(self):
        self.child = Child()
    
    @property
    def get_child(self):
        return Child()
```
        
**Second.py** ->
```python
import ...

Parent().child.print_word('not working')    #inlay is not working when called from other module
        
```

**Comment by hostar** [comment]
<del>I spent some time over this, but this is where I am stuck: ~~
this line:
https://github.com/hostar/python-inlay-putter/blob/master/src/main/java/io/github/hostar/pythonInlay/PythonParametersInlayProvider.java#L102
</del>
<del>
should return the reference in the other file, but it just does not do it, even though it works in GUI.
I suspect the problem is that it is using cache instead of doing attempt for new resolve.</del>
<del>
If you or someone want to try to fix it, just clone the repo and open the folder in the IntelliJ. After opening, run [runIde] configuration in debug mode which will allow you to stop on breakpoints, inspect variables etc.
The first run will probably take a while because the whole PyCharm will be downloaded again.</del>

**Comment by hostar** [comment]
Turns out, people developing the IDE had the same problem and managed to fix it in the Python plugin.
So I took the part of code which was useful for me and the minimal example now works.
Try here: https://github.com/hostar/python-inlay-putter/releases/tag/0.0.6

**Comment by teodor-t-tenev** [comment]
Great job @hostar. Now it works like a charm ^_^
